name: Install Dependencies
on:
  workflow_call:
    inputs:
      mode:
        description: 'Either dev or prod. Dev will install dev dependencies, prod will remove dev dependencies.'
        required: true
        default: 'dev'
        type: string

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4

      - name: Cache Composer packages
        id: cache-composer
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ inputs.mode }}-${{ hashFiles('composer.lock') }}

      - if: steps.cache-composer.outputs.cache-hit != 'true'
        name: Validate composer.json and composer.lock
        run: composer validate --strict
        shell: bash

      # Install dependencies
      - if: steps.cache-composer.outputs.cache-hit != 'true'
        name: Install dependencies
        run: |
          if [ "${{ inputs.mode }}" = "dev" ]; then
            composer install --prefer-dist --no-interaction --no-progress
          else
            composer install --no-dev --prefer-dist --no-progress --no-suggest --ignore-platform-reqs --optimize-autoloader --classmap-authoritative
          fi
        shell: bash

      - name: Cache all Deps
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            vendor
          key: deps-${{ inputs.mode }}-${{ hashFiles('composer.lock') }}