name: Test/Analyse

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

jobs:
  call-install-deps:
    uses: ./.github/workflows/install-deps.yml
    with:
      mode: 'dev'
    secrets: inherit

  test:
    runs-on: ubuntu-latest
    needs: call-install-deps

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load Cache
        uses: actions/cache@v3
        with:
          path: |
            vendor
            node_modules
            dist
          key: deps-dev-${{ hashFiles('composer.lock') }}-${{ hashFiles('package-lock.json') }}
          fail-on-cache-miss: true
        id: cache

      - name: Build assets
        run: |
          npm run production

      - name: PHPSTAN
        run: composer run static-analyse

#      - name: Run integration Tests
#        run: |
#          npm run test:e2e